ur5_arm:
#  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
#  kinematics_service: srv_kinematics_plugin/SrvKinematicsPlugin
#  kinematics_solver_search_resolution: 0.005
#  kinematics_solver_timeout: 0.005
#  position_only_ik: True

# own ur5 kinematics plugin from ~ur_kinematics/ur_moveit_plugins.xml
  kinematics_solver: ur_kinematics/UR5KinematicsPlugin
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
  max_solver_iterations: 100
#  kinematics_solver_attempts: 3
