generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.03

# Settings for ros_control hardware interface
hardware_interface:
  sim_control_mode: 0
  joints:
  - $(arg tf_prefix)shoulder_pan_joint
  - $(arg tf_prefix)shoulder_lift_joint
  - $(arg tf_prefix)elbow_joint
  - $(arg tf_prefix)wrist_1_joint
  - $(arg tf_prefix)wrist_2_joint
  - $(arg tf_prefix)wrist_3_joint