#add direction to launch file: 
#<rosparam file="$(find ur5_controller)/config/ur5_controller.yaml" command="load" subst_value="true"/>

# Velocity Controller ------------output:velocity-----------------
#shoulder_pan_joint_velocity_controller: #input: one joint position
#  type: "velocity_controllers/JointPositionController"
#  joint: $(arg tf_prefix)shoulder_pan_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}
#shoulder_lift_joint_velocity_controller:
#  type: "velocity_controllers/JointPositionController"
#  joint: $(arg tf_prefix)shoulder_lift_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}
#elbow_joint_velocity_controller:
#  type: "velocity_controllers/JointPositionController"
#  joint: $(arg tf_prefix)elbow_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}
#wrist_1_joint_velocity_controller:
#  type: "velocity_controllers/JointPositionController"
#  joint: $(arg tf_prefix)wrist_1_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}
#wrist_2_joint_velocity_controller:
#  type: "velocity_controllers/JointPositionController"
#  joint: $(arg tf_prefix)wrist_2_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}
#wrist_3_joint_velocity_controller:
#  type: "velocity_controllers/JointPositionController"
#  joint: $(arg tf_prefix)wrist_3_joint
#  pid: {p: 100.0, i: 0.01, d: 10.0}
#
shoulder_pan_joint_velocity_controller: #input: one joint velocity
  type: "velocity_controllers/JointVelocityController"
  joint: $(arg tf_prefix)shoulder_pan_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
shoulder_lift_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: $(arg tf_prefix)shoulder_lift_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
elbow_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: $(arg tf_prefix)elbow_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
wrist_1_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: $(arg tf_prefix)wrist_1_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
wrist_2_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: $(arg tf_prefix)wrist_2_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}
wrist_3_joint_velocity_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: $(arg tf_prefix)wrist_3_joint
  pid: {p: 100.0, i: 0.01, d: 10.0}

# Pass an array of joint velocities directly to the joints
joint_group_vel_controller:
   type: velocity_controllers/JointGroupVelocityController
   joints:
    - $(arg tf_prefix)shoulder_pan_joint
    - $(arg tf_prefix)shoulder_lift_joint
    - $(arg tf_prefix)elbow_joint
    - $(arg tf_prefix)wrist_1_joint
    - $(arg tf_prefix)wrist_2_joint
    - $(arg tf_prefix)wrist_3_joint
   gains:
    #!!These values have not been optimized!!
    $(arg tf_prefix)shoulder_pan_joint:  {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)shoulder_lift_joint: {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)elbow_joint:         {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)wrist_1_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)wrist_2_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}
    $(arg tf_prefix)wrist_3_joint:       {p: 5.0,  i: 0.05, d: 0.1, i_clamp: 1}

#arm_velocity_controller: #input: one joint position
#  type: velocity_controllers/JointPositionController
#  joints:
#   - $(arg tf_prefix)shoulder_pan_joint
#    - $(arg tf_prefix)shoulder_lift_joint
#    - $(arg tf_prefix)elbow_joint
#    - $(arg tf_prefix)wrist_1_joint
#    - $(arg tf_prefix)wrist_2_joint
#    - $(arg tf_prefix)wrist_3_joint
#  pid_gains: {p: 100.0, i: 0.01, d: 10.0}
